server:
  port: ${PORT:8080}
  servlet:
    context-path: /docter-anywhere

spring:
  datasource:
    url: jdbc:mysql://${DB_HOST:localhost}:${DB_PORT:3306}/${DB_NAME:mydatabase}?allowPublicKeyRetrieval=true
    username: ${DB_USERNAME:myuser}
    password: ${DB_PASSWORD:secret}
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  flyway:
    enable: true
    baseline-on-migrate: true
    check-location: false
    locations: classpath:db/migration
#  security:
#    user:
#      name: your_username
#      password: your_password

logging:
  level:
    root: DEBUG
    org.springframework: DEBUG
